In [37]:
import numpy as np

# Create an array with values 1 to 15
arr = np.arange(1, 16)

# Reshape it into a 3-by-5 array
arr = arr.reshape(3, 5)

#a) Select row 2
row_2 = arr[1]

#b) Select the column 4.
column_4 = arr[:, 3]

#c) Select rows 0 and 1.
rows_0_and_1 = arr[:2]

#d) Select columns 2–4.
columns_2_to_4 = arr[:, 1:5]

#e) Select the element that is in row1 and column4
element_row1_column4 = arr[1, 4]

#f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
rows_1_and_2_columns_0_2_4 = arr[1:3, [0, 2, 4]]

In [35]:
# Printing out the results

print("a) Select row 2 \n\n Row 2:", row_2)

print("\n b) Select the column 4\n Column 4:", column_4)

print("\n c) Select rows 0 and 1\n Rows 0 and 1:\n", rows_0_and_1)

print("\n d) Select columns 2–4\n Columns 2 to 4:\n", columns_2_to_4)

print("\n e) Select the element that is in row 1 and column 4\n Element in row1 and column4:", element_row1_column4)

print("\n f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4\n Selected elements:\n", rows_1_and_2_columns_0_2_4)

a) Select row 2

 Row 2: [ 6  7  8  9 10]

 b) Select the column 4
 Column 4: [ 4  9 14]

 c) Select rows 0 and 1
 Rows 0 and 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 d) Select columns 2–4
 Columns 2 to 4:
 [[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]

 e) Select the element that is in row 1 and column 4
 Element in row1 and column4: 10

 f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4
 Selected elements:
 [[ 6  8 10]
 [11 13 15]]

In [28]:
import numpy as np

# Define the arrays
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# a) Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2
array3 = np.vstack((array1, array2))

# b) Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1
array4 = np.hstack((array1, array2))

# c) Use vertical stacking with two copies of array4 to create a 4-by-4 array named array5
array5 = np.vstack((array4, array4))

# d) Use horizontal stacking with two copies of array3 to create a 4-by-4 array named array6
array6 = np.hstack((array3, array3))

In [36]:
# Printing out the results
print("\n a) Vertical stacking of array1 on top of array2\n Array3:\n", array3)

print("\n b) Horizontal stacking of array1 and array2\n Array4:\n", array4)

print("\n c) Vertical stacking of two copies of array4\n Array5:\n", array5)

print("\n d) Horizontal stacking of two copies of array3\n Array6:\n", array6)

 a) Vertical stacking of array1 on top of array2
 Array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

 b) Horizontal stacking of array1 and array2
 Array4:
 [[0 1 4 5]
 [2 3 6 7]]

 c) Vertical stacking of two copies of array4
 Array5:
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

 d) Horizontal stacking of two copies of array3
 Array6:
 [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]

In [34]:
import numpy as np

# Createing heckerboard pattern
pattern = np.array([['_', '*'], ['_', '*']])

checkerboard = np.tile(pattern, (6, 8))

# Print the checkerboard pattern
print('\n'.join([' '.join(row) for row in checkerboard]))

_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *
_ * _ * _ * _ * _ * _ * _ * _ *